
logging:
  level:
    org.springframework.security: DEBUG

access_token:
  facebook: EAAH0LwYZBkoQBAHvuV4hLN1tHUBPgI1LrH9oKAoFrJw7YNL1XyInlk8XimlAZC8RczBHe79dWIxvaBRqGO1F1dhQ3qwg1e94PUQh43JtsjFMnwp6pE03V1es5uY0dNP3HLVDXZAeUYISqI2tizc1BQDS7MgtNOhOKcJavvYWAZDZD
  twitter:
    oauthToken: 707105302416523264-VqBQxyxdn12AR2AbyTO4azQXmALIBV0
    oauthTokenSecret: FzerMdzmxtkBhBBMoGVEt65zEgnbX1wDjE257Lzd0ShG0

facebook:
  appId: 469354166884422
  appSecret: 0d7f92e87dc2322c9364fa302d436be5
#  appId: 2162335307350013
#  appSecret: b89fc73f8231e7399d75c0fe0bff0b69

server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-password: overseasapp
    key-store-password: overseasapp